version: "3"

services:
  mern-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - mern-back
    networks:
      - mernnetwork

  mern-back:
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./back:/back
      - /back/node_modules
    depends_on:
      - mongodb
    networks:
      - mernnetwork

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - "5000:5000"
    command: mongod --noauth --smallfiles
    networks:
      - mernnetwork

networks:
  mernnetwork:
    driver: bridge